"use strict";

// D16: one framework-constant map, owned only by the kernel.
const { deepFreeze } = require("./contracts");

const REQUIRED_CHECK_IDS = deepFreeze({
  COMMON: [
    "1A.IDENTITY.INVOCATION", "1A.IDENTITY.HEAD", "1A.IDENTITY.BASE",
    "1A.POLICY.ROOT", "1A.POLICY.ANCHOR", "1A.POLICY.CURRENT", "1A.POLICY.CAPABILITIES", "1A.POLICY.GATE_ANCHOR", "1A.POLICY.EFFECTIVE",
    "1A.TARGET.PROTECTED",
    "1A.DIFF.CHANGED_FILES", "1A.DIFF.PLATFORM_AGREEMENT",
    "1A.SCOPE.POLICY", "1A.SECRETS.POLICY", "1A.SCOPE.PROPOSAL", "1A.SCOPE.FORBIDDEN", "1A.SCOPE.ALLOWED", "1A.SCOPE.PROTECTED",
    "1A.SECRETS.SCAN", "1A.SECRETS.SUPPRESSIONS",
    "1B.MARKDOWN.FILES", "1B.MARKDOWN.FENCES", "1B.MARKDOWN.TABLES", "1B.MARKDOWN.HEADINGS", "1B.MARKDOWN.ANCHORS", "1B.MARKDOWN.LINKS", "1B.MARKDOWN.POLICY",
    "1C.EVIDENCE.CONFIG", "1C.EVIDENCE.STRUCTURE", "1C.EVIDENCE.PREMISES", "1C.EVIDENCE.PROPAGATION", "1C.EVIDENCE.PROMOTION_WORDING", "1C.EVIDENCE.ROW_INDEX",
    "1D.CONSISTENCY.CONFIG", "1D.CONSISTENCY.COUNTS", "1D.CONSISTENCY.TAXONOMY", "1D.CONSISTENCY.METHOD",
    "1E.DELTA.DOMAIN_SET",
    "1F.CI",
  ],
  PR_REVIEW: ["1A.IDENTITY.TARGET_TIP", "1A.IDENTITY.RANGE", "1A.IDENTITY.EXPECTED_BASE", "1A.IDENTITY.WORKFLOW_ANCHOR"],
  POST_MERGE: ["1A.IDENTITY.MERGE_ON_TARGET", "1A.IDENTITY.TOPOLOGY", "1A.IDENTITY.MERGED_HEAD"],
});

module.exports = { REQUIRED_CHECK_IDS };
