/**
 * GOV-AUTO-1 Wave 0 -- shared kernel contracts (constants, reason codes, errors).
 *
 * Binding source: docs/gov-auto-1-design-reconciliation-v1.md (sections 6, 7,
 * 22). This module holds only frozen data and one error class; it performs no
 * I/O and inspects no repository. Wave 0 contains no repository-specific check.
 */

"use strict";

function deepFreeze(value) {
  if (value !== null && typeof value === "object" && !Object.isFrozen(value)) {
    Object.freeze(value);
    for (const key of Object.keys(value)) deepFreeze(value[key]);
  }
  return value;
}

const STATUS = deepFreeze({
  PASS: "PASS",
  FAIL: "FAIL",
  CONFIGURATION_ERROR: "CONFIGURATION_ERROR",
  HUMAN_REVIEW_REQUIRED: "HUMAN_REVIEW_REQUIRED",
  INCOMPLETE: "INCOMPLETE",
  NOT_APPLICABLE: "NOT_APPLICABLE",
});

// Aggregation precedence, highest first (design section 22). NOT_APPLICABLE is
// neutral and is deliberately absent: it never outranks or equals PASS.
const STATUS_PRECEDENCE = deepFreeze([
  STATUS.CONFIGURATION_ERROR,
  STATUS.FAIL,
  STATUS.INCOMPLETE,
  STATUS.HUMAN_REVIEW_REQUIRED,
  STATUS.PASS,
]);

// Executable ownership. 1G is independent validation, not an owner (design 18).
const OWNER_STAGES = deepFreeze(["KERNEL", "1A", "1B", "1C", "1D", "1E", "1F"]);

const READINESS = deepFreeze({
  READY: "READY",
  HUMAN_REVIEW_REQUIRED: "HUMAN_REVIEW_REQUIRED",
  NOT_READY: "NOT_READY",
});

const EDGE_KINDS = deepFreeze(["DERIVED_VALUE", "REFERENCE", "MEANING"]);
const REVIEW_MODES = deepFreeze(["DEEP_REVIEW_REQUIRED", "PRESERVATION_CHECK_ONLY"]);
const EFFECTIVE_LEVELS = deepFreeze([
  "PRESERVATION_CHECK_ONLY",
  "DEEP_REVIEW_REQUIRED",
  "HUMAN_REVIEW_REQUIRED",
]);
const RANGE_MODES = deepFreeze(["PR_REVIEW", "POST_MERGE"]);

// Stable machine-readable reason codes needed by the Wave 0 kernel only.
const REASON = deepFreeze({
  OK: "OK",
  // manifest / JSON
  INVALID_MANIFEST_ENCODING: "INVALID_MANIFEST_ENCODING",
  MANIFEST_TOO_LARGE: "MANIFEST_TOO_LARGE",
  MANIFEST_JSON_INVALID: "MANIFEST_JSON_INVALID",
  DUPLICATE_JSON_KEY: "DUPLICATE_JSON_KEY",
  JSON_DEPTH_EXCEEDED: "JSON_DEPTH_EXCEEDED",
  MANIFEST_UNKNOWN_FIELD: "MANIFEST_UNKNOWN_FIELD",
  MANIFEST_FIELD_MISSING: "MANIFEST_FIELD_MISSING",
  MANIFEST_TYPE_INVALID: "MANIFEST_TYPE_INVALID",
  // schema / capability metadata
  SCHEMA_VERSION_MISSING: "SCHEMA_VERSION_MISSING",
  SCHEMA_VERSION_INVALID: "SCHEMA_VERSION_INVALID",
  SCHEMA_VERSION_BELOW_MINIMUM: "SCHEMA_VERSION_BELOW_MINIMUM",
  CAPABILITY_UNAVAILABLE_ON_TARGET: "CAPABILITY_UNAVAILABLE_ON_TARGET",
  TARGET_SCHEMA_RANGE_UNAVAILABLE: "TARGET_SCHEMA_RANGE_UNAVAILABLE",
  TARGET_SCHEMA_RANGE_INVALID: "TARGET_SCHEMA_RANGE_INVALID",
  CAPABILITY_ID_INVALID: "CAPABILITY_ID_INVALID",
  FRAMEWORK_METADATA_INVALID: "FRAMEWORK_METADATA_INVALID",
  // domain / dependency graph
  DOMAIN_DECLARATION_INVALID: "DOMAIN_DECLARATION_INVALID",
  DEPENDENCY_DECLARATION_MISSING: "DEPENDENCY_DECLARATION_MISSING",
  DEPENDENCY_UNKNOWN: "DEPENDENCY_UNKNOWN",
  DEPENDENCY_DISABLED: "DEPENDENCY_DISABLED",
  DEPENDENCY_SELF: "DEPENDENCY_SELF",
  DEPENDENCY_KIND_INVALID: "DEPENDENCY_KIND_INVALID",
  DEPENDENCY_EDGE_DUPLICATE: "DEPENDENCY_EDGE_DUPLICATE",
  DEPENDENCY_CYCLE: "DEPENDENCY_CYCLE",
  DERIVED_FROM_NOT_IN_DEPENDS_ON: "DERIVED_FROM_NOT_IN_DEPENDS_ON",
  DOMAIN_DUPLICATE: "DOMAIN_DUPLICATE",
  // safety primitives
  UNSAFE_PATH: "UNSAFE_PATH",
  PROCESS_INVALID_REQUEST: "PROCESS_INVALID_REQUEST",
  PROCESS_TIMEOUT: "PROCESS_TIMEOUT",
  PROCESS_FAILURE: "PROCESS_FAILURE",
  PROCESS_OUTPUT_LIMIT: "PROCESS_OUTPUT_LIMIT",
  PROCESS_SPAWN_ERROR: "PROCESS_SPAWN_ERROR",
  // result records / aggregation
  RESULT_RECORD_INVALID: "RESULT_RECORD_INVALID",
  DUPLICATE_CHECK_ID: "DUPLICATE_CHECK_ID",
  SUBJECT_MISMATCH: "SUBJECT_MISMATCH",
  DOMAIN_RESULT_MISSING: "DOMAIN_RESULT_MISSING",
  DOMAIN_RESULT_DUPLICATE: "DOMAIN_RESULT_DUPLICATE",
  DOMAIN_RESULT_UNKNOWN: "DOMAIN_RESULT_UNKNOWN",
  DOMAIN_PROJECTION_MISMATCH: "DOMAIN_PROJECTION_MISMATCH",
  APPLICABILITY_NOT_PROVEN: "APPLICABILITY_NOT_PROVEN",
  NO_PASSING_EVIDENCE: "NO_PASSING_EVIDENCE",
  // Wave 1 / 1A: trusted invocation, identity, base derivation (design section 14)
  TRUSTED_CONTEXT_INVALID: "TRUSTED_CONTEXT_INVALID",
  OPERATOR_INVOCATION: "OPERATOR_INVOCATION",
  HEAD_UNAVAILABLE: "HEAD_UNAVAILABLE",
  HEAD_MISMATCH: "HEAD_MISMATCH",
  TARGET_TIP_UNAVAILABLE: "TARGET_TIP_UNAVAILABLE",
  TARGET_TIP_MISMATCH: "TARGET_TIP_MISMATCH",
  DEFAULT_BRANCH_UNAVAILABLE: "DEFAULT_BRANCH_UNAVAILABLE",
  BASE_NOT_ESTABLISHED: "BASE_NOT_ESTABLISHED",
  DEGENERATE_RANGE: "DEGENERATE_RANGE",
  BASE_MISMATCH: "BASE_MISMATCH",
  TARGET_NOT_PROTECTED: "TARGET_NOT_PROTECTED",
  POLICY_INVALID: "POLICY_INVALID",
  POLICY_OUTDATED: "POLICY_OUTDATED",
  NO_BASE_TRUST_ANCHOR: "NO_BASE_TRUST_ANCHOR",
  NO_BASE_GATE_ANCHOR: "NO_BASE_GATE_ANCHOR",
  GATE_MANIFEST_MISSING: "GATE_MANIFEST_MISSING",
  GOVERNANCE_CONFIG: "GOVERNANCE_CONFIG",
  WORKFLOW_IDENTITY_UNAVAILABLE: "WORKFLOW_IDENTITY_UNAVAILABLE",
  INVOCATION_NOT_ANCHORED: "INVOCATION_NOT_ANCHORED",
  // Wave 1 / 1A: post-merge topology
  MERGE_NOT_ON_TARGET: "MERGE_NOT_ON_TARGET",
  TOPOLOGY_UNEXPECTED: "TOPOLOGY_UNEXPECTED",
  BASE_NOT_ON_TARGET_HISTORY: "BASE_NOT_ON_TARGET_HISTORY",
  MERGED_HEAD_MISMATCH: "MERGED_HEAD_MISMATCH",
  // Wave 1 / 1A: changed-file set
  CHANGED_PATH_INVALID: "CHANGED_PATH_INVALID",
  DIFF_COMPUTATION_FAILED: "DIFF_COMPUTATION_FAILED",
  PLATFORM_FILE_LIST_INCOMPLETE: "PLATFORM_FILE_LIST_INCOMPLETE",
  PLATFORM_FILE_LIST_ANOMALY: "PLATFORM_FILE_LIST_ANOMALY",
  DIFF_PATHS_MISMATCH: "DIFF_PATHS_MISMATCH",
  DIFF_EMPTY_UNEXPECTED: "DIFF_EMPTY_UNEXPECTED",
  EMPTY_DIFF_CONFIRMED: "EMPTY_DIFF_CONFIRMED",
  // Wave 1 / 1A: scope, secrets, suppressions
  SCOPE_FORBIDDEN_PATH: "SCOPE_FORBIDDEN_PATH",
  SCOPE_OUTSIDE_ALLOWED: "SCOPE_OUTSIDE_ALLOWED",
  SCOPE_POLICY_UNAVAILABLE: "SCOPE_POLICY_UNAVAILABLE",
  SCOPE_LOOSENING_PROPOSED: "SCOPE_LOOSENING_PROPOSED",
  SECRET_FOUND: "SECRET_FOUND",
  SECRET_HEURISTIC_HIT: "SECRET_HEURISTIC_HIT",
  SUPPRESSION_INVALID: "SUPPRESSION_INVALID",
  SUPPRESSION_PROPOSED: "SUPPRESSION_PROPOSED",
  SCAN_BOUND_EXCEEDED: "SCAN_BOUND_EXCEEDED",
  SCAN_INPUT_INVALID: "SCAN_INPUT_INVALID",
  // Wave 1 / 1B: Markdown and reference integrity
  CHANGED_FILES_INPUT_INVALID: "CHANGED_FILES_INPUT_INVALID",
  MARKDOWN_ENCODING_INVALID: "MARKDOWN_ENCODING_INVALID",
  MARKDOWN_STRUCTURE_INVALID: "MARKDOWN_STRUCTURE_INVALID",
  MARKDOWN_BOUND_EXCEEDED: "MARKDOWN_BOUND_EXCEEDED",
  MARKDOWN_UNREADABLE: "MARKDOWN_UNREADABLE",
  LINK_TARGET_MISSING: "LINK_TARGET_MISSING",
  LINK_ESCAPES_ROOT: "LINK_ESCAPES_ROOT",
  ANCHOR_DANGLING: "ANCHOR_DANGLING",
  ID_FAMILY_CONFIG_INVALID: "ID_FAMILY_CONFIG_INVALID",
  REFERENCE_DANGLING: "REFERENCE_DANGLING",
  REFERENCE_DUPLICATE: "REFERENCE_DUPLICATE",
  REFERENCE_MALFORMED: "REFERENCE_MALFORMED",
});

/**
 * Raised only for a programming/usage error against a safety primitive (an
 * unsafe path or a malformed process request). The message is bounded and never
 * embeds caller-supplied values verbatim beyond a short redacted excerpt.
 */
class GovernanceSafetyError extends Error {
  constructor(reasonCode, message) {
    super(`${reasonCode}: ${message}`);
    this.name = "GovernanceSafetyError";
    this.reasonCode = reasonCode;
  }
}

const LIMITS = deepFreeze({
  maxManifestBytes: 1024 * 1024,
  maxJsonDepth: 32,
  maxStringLength: 4096,
  maxArrayLength: 1024,
  maxDomains: 256,
  maxDetailLength: 500,
  maxEvidenceRefs: 32,
});

module.exports = {
  deepFreeze,
  STATUS,
  STATUS_PRECEDENCE,
  OWNER_STAGES,
  READINESS,
  EDGE_KINDS,
  REVIEW_MODES,
  EFFECTIVE_LEVELS,
  RANGE_MODES,
  REASON,
  LIMITS,
  GovernanceSafetyError,
};
