"use strict";

/**
 * Roadmap #19.7B - immutable Cypress historical equivalence regression
 * barrier.
 *
 * PURPOSE
 *
 * Roadmap #19.6 extracted raw Cypress/Mochawesome artifact handling out of
 * collect-context.js into scripts/ai/adapters/cypress-adapter.js. That
 * extraction was verified once, manually, during #19.6's own review. This
 * file converts that one-time manual proof into a committed, immutable,
 * CI-enforced regression barrier: for a representative matrix of raw
 * Cypress/Mochawesome artifact inputs, the CURRENT CypressAdapter must
 * keep producing the exact same {testResults, failedTests, warnings}
 * that the HISTORICAL, pre-adapter collect-context.js produced for the
 * same input, before any extraction ever happened.
 *
 * HISTORICAL ORACLE
 *
 *   1aff8f69484b7df5a293e7f1761f580fa2d3c9b0
 *
 * This is the exact commit immediately before Roadmap #19.6 (the last
 * commit where collect-context.js still parsed Mochawesome/Cypress
 * screenshots directly). It is the *only* source of truth for every
 * golden literal below - every scenario in this file was captured by
 * running the literal historical collect-context.js from that commit
 * (in a disposable, detached `git worktree`, never committed) against
 * the exact same fixture used against current code, machine-comparing
 * the two outputs with assert.deepStrictEqual, and only then transcribing
 * the (proven-equal) result as the golden literal below. The historical
 * commit's code does NOT run as part of this file, or any other part of
 * normal test execution/CI - it was executed once, by hand, during
 * authoring, and is otherwise preserved only in Git history. See the
 * per-scenario comments for what each one specifically protects.
 *
 * NORMALIZATION CONTRACT (do not add fields here without equally strong
 * justification - see comments below for why each one is what it is):
 *
 *   generatedAt: DROPPED - `new Date().toISOString()`, always different
 *     between any two invocations of collect-context.js; no other field
 *     is normalized.
 *
 * Everything else is CONTROLLED (fixed synthetic env vars so historical
 * and current metadata match exactly, never a "close enough" comparison)
 * or explicitly out of the frozen surface by design (see
 * collect-context.test.js's own S1/S11 full-context scenarios for the
 * `relevantFiles` projection rationale - this file's own scenarios never
 * touch `relevantFiles` at all, since raw artifact extraction is entirely
 * upstream of it).
 *
 * MULTI-REPORT ORDERING: `fs.readdirSync()`'s enumeration order for
 * multiple non-`report.json` files was never sorted by the historical
 * implementation, and #19.6 deliberately preserved that (see S10 below).
 * This file therefore explicitly does NOT freeze array positional order
 * for the one multi-report scenario - only order-independent aggregate
 * membership.
 *
 * WARNINGS remain positional/order-sensitive everywhere else - warning
 * ORDER is itself observable, historically-anchored behavior. The one
 * exception is the malformed-JSON warning's own diagnostic tail (S8),
 * which is generated by the V8 engine's JSON.parse, not by this
 * project - its exact English wording is excluded from the frozen
 * surface (RUNTIME_VOLATILE_WARNING_PROJECTION, see S8's own comment),
 * since this repository's CI already pins a different Node version than
 * local development and V8's diagnostic wording is not a stable
 * contract. The warning's project-owned prefix (path + "Could not
 * parse") remains frozen exactly.
 *
 * GOLDEN IMMUTABILITY: there is no update/regeneration command in this
 * repository for these goldens, deliberately. A golden literal below may
 * only change via an explicit, reviewed PR that states why the historical
 * contract is intentionally migrating - never merely to make CI green.
 */

const { test } = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const cypressAdapter = require("./adapters/cypress-adapter");

const HISTORICAL_ORACLE_COMMIT = "1aff8f69484b7df5a293e7f1761f580fa2d3c9b0";
const ROOT = path.resolve(__dirname, "..", "..");
// Roadmap FPI-2: cypressAdapter.collect() no longer derives its own target
// repository root from this module's __dirname - every call below now
// supplies an explicit `root: {lexicalRoot, realRoot}` boundary (see
// scripts/ai/repository-root.js), matching production's own
// collect-context.js wiring. This has no bearing on the historical-oracle
// equivalence itself: every scenario here uses an isolated reportsDir with
// no screenshot attachments, so `root` is never actually consulted by
// extractFailedTests()/summarizeTestResults() beyond being a valid object.
const TEST_ROOT = Object.freeze({ lexicalRoot: ROOT, realRoot: fs.realpathSync(ROOT) });

function tmpReportsDir() {
  return fs.mkdtempSync(path.join(os.tmpdir(), "cypress-equivalence-reports-"));
}

function writeReport(dir, filename, reportObject) {
  fs.writeFileSync(path.join(dir, filename), JSON.stringify(reportObject));
}

// --- S1: mixed result set (captured from oracle commit HISTORICAL_ORACLE_COMMIT) --
// Protects: totals aggregation, failedTests extraction (only the failed
// test, never the passed/pending ones), and screenshot resolution, all
// together in one representative "normal" run.

test("S1 mixed result: current adapter matches the historical oracle for pass+fail+pending+screenshot", (t) => {
  const reportsDir = tmpReportsDir();
  // Screenshot resolution is only proven ROOT-relative (matching real
  // production behavior) when screenshotsDir is the real
  // cypress/screenshots directory - an overridden temp directory would
  // leak an absolute machine-specific path into the result, since
  // normalizeSpecPath only strips a path that starts with this
  // collector's own ROOT (see context-utils.js). This mirrors the
  // pre-existing resolveScreenshotPath tests in cypress-adapter.test.js
  // that also use the real path for the same reason.
  //
  // Cleanup is deliberately scoped to ONLY this test's own uniquely-named
  // "s1_mixed.cy.js" subdirectory, never the shared cypress/screenshots
  // ROOT itself - cypress-adapter.test.js's own pre-existing screenshot
  // tests (and S5 below) also read/write under that same shared root
  // concurrently (Node's test runner runs separate test files as
  // concurrent processes by default), so a whole-root rmSync here could
  // delete another file's in-flight fixture out from under it. Since
  // resolveScreenshotPath()/collect() only ever touch
  // <screenshotsDir>/<basename(specFile)>/, deleting just that one
  // basename subdirectory is sufficient and never collides with any
  // other test's differently-named subdirectory.
  const specDir = path.join(ROOT, "cypress", "screenshots", "s1_mixed.cy.js");
  t.after(() => {
    fs.rmSync(reportsDir, { recursive: true, force: true });
    fs.rmSync(specDir, { recursive: true, force: true });
  });
  try {
    writeReport(reportsDir, "report.json", {
      stats: { tests: 3, passes: 1, failures: 1, pending: 1, duration: 42 },
      results: [
        {
          file: "/cypress/e2e/tests/s1_mixed.cy.js",
          suites: [
            {
              title: "S1 Suite",
              suites: [],
              tests: [
                { title: "passes fine", state: "passed" },
                { title: "is pending", state: "pending" },
                {
                  title: "fails here",
                  state: "failed",
                  duration: 12,
                  err: { message: "AssertionError: boom", estack: "AssertionError: boom\n  at x" },
                },
              ],
            },
          ],
        },
      ],
    });
    fs.mkdirSync(specDir, { recursive: true });
    fs.writeFileSync(path.join(specDir, "S1 Suite -- fails here (failed).png"), "");

    const result = cypressAdapter.collect({ root: TEST_ROOT, reportsDir });

    // Historical golden (oracle: HISTORICAL_ORACLE_COMMIT).
    assert.deepStrictEqual(result, {
      testResults: {
        found: true,
        totals: { tests: 3, passed: 1, failed: 1, pending: 1, duration: 42 },
        specs: [{ specFile: "cypress/e2e/tests/s1_mixed.cy.js", tests: 3, passed: 1, failed: 1, pending: 1, duration: 42 }],
      },
      failedTests: [
        {
          title: "fails here",
          fullTitle: null,
          suite: "S1 Suite",
          specFile: "cypress/e2e/tests/s1_mixed.cy.js",
          status: "failed",
          duration: 12,
          error: { message: "AssertionError: boom", stack: "AssertionError: boom\n  at x" },
          screenshot: path.posix.join("cypress/screenshots/s1_mixed.cy.js", "S1 Suite -- fails here (failed).png"),
        },
      ],
      warnings: [],
    });
  } finally {
    fs.rmSync(reportsDir, { recursive: true, force: true });
  }
});

// --- S2: nested suites (captured from oracle commit) ------------------
// Protects: depth-first suite traversal and suite-title accumulation
// ("Outer > Inner"), independent of failure/error/screenshot handling.

test("S2 nested suites: current adapter matches the historical oracle for depth-first suite-title accumulation", () => {
  const reportsDir = tmpReportsDir();
  try {
    writeReport(reportsDir, "report.json", {
      stats: { tests: 1, passes: 0, failures: 1, pending: 0, duration: 5 },
      results: [
        {
          file: "/cypress/e2e/tests/s2_nested.cy.js",
          suites: [
            {
              title: "Outer",
              tests: [],
              suites: [
                {
                  title: "Inner",
                  tests: [{ title: "deep failure", state: "failed", duration: 5, err: { message: "deep err", estack: "deep err\n at y" } }],
                  suites: [],
                },
              ],
            },
          ],
        },
      ],
    });

    const result = cypressAdapter.collect({ root: TEST_ROOT, reportsDir });

    assert.deepStrictEqual(result, {
      testResults: {
        found: true,
        totals: { tests: 1, passed: 0, failed: 1, pending: 0, duration: 5 },
        specs: [{ specFile: "cypress/e2e/tests/s2_nested.cy.js", tests: 1, passed: 0, failed: 1, pending: 0, duration: 5 }],
      },
      failedTests: [
        {
          title: "deep failure",
          fullTitle: null,
          suite: "Outer > Inner",
          specFile: "cypress/e2e/tests/s2_nested.cy.js",
          status: "failed",
          duration: 5,
          error: { message: "deep err", stack: "deep err\n at y" },
          screenshot: null,
        },
      ],
      warnings: [],
    });
  } finally {
    fs.rmSync(reportsDir, { recursive: true, force: true });
  }
});

// --- S3: fail/pending defensive fallback (captured from oracle commit) --
// Protects: the historical `test.fail === true && test.pending !== true`
// defensive fallback (not just `test.state === "failed"`), and pending
// exclusion even when `fail === true`.

test("S3 fail/pending fallback: current adapter matches the historical oracle for the fail/pending defensive semantics", () => {
  const reportsDir = tmpReportsDir();
  try {
    writeReport(reportsDir, "report.json", {
      stats: { tests: 2, passes: 0, failures: 1, pending: 1, duration: 3 },
      results: [
        {
          file: "/cypress/e2e/tests/s3_fallback.cy.js",
          suites: [
            {
              title: "S3 Suite",
              suites: [],
              tests: [
                { title: "fails via flag", fail: true, pending: false, err: { message: "flag failure" } },
                { title: "pending via flag", fail: true, pending: true, err: { message: "should be excluded" } },
              ],
            },
          ],
        },
      ],
    });

    const result = cypressAdapter.collect({ root: TEST_ROOT, reportsDir });

    assert.deepStrictEqual(result, {
      testResults: {
        found: true,
        totals: { tests: 2, passed: 0, failed: 1, pending: 1, duration: 3 },
        specs: [{ specFile: "cypress/e2e/tests/s3_fallback.cy.js", tests: 2, passed: 0, failed: 1, pending: 1, duration: 3 }],
      },
      failedTests: [
        {
          title: "fails via flag",
          fullTitle: null,
          suite: "S3 Suite",
          specFile: "cypress/e2e/tests/s3_fallback.cy.js",
          status: "failed",
          duration: null,
          error: { message: "flag failure", stack: null },
          screenshot: null,
        },
      ],
      warnings: [],
    });
  } finally {
    fs.rmSync(reportsDir, { recursive: true, force: true });
  }
});

// --- S4: error/stack matrix (captured from oracle commit) -------------
// Protects: estack preference over stack, stack-only fallback, null when
// neither is present, and the 4000-char truncation marker - all four in
// one report so their relative behavior is proven together.

test("S4 error/stack matrix: current adapter matches the historical oracle for estack/stack/truncation semantics", () => {
  const reportsDir = tmpReportsDir();
  const longStack = "at frame\n".repeat(600); // well over MAX_STACK_CHARS (4000)
  try {
    writeReport(reportsDir, "report.json", {
      stats: { tests: 4, passes: 0, failures: 4, pending: 0, duration: 4 },
      results: [
        {
          file: "/cypress/e2e/tests/s4_errors.cy.js",
          suites: [
            {
              title: "S4 Suite",
              suites: [],
              tests: [
                { title: "A estack wins", state: "failed", err: { message: "mA", estack: "estackA", stack: "stackA-should-not-appear" } },
                { title: "B stack fallback", state: "failed", err: { message: "mB", stack: "stackB-only" } },
                { title: "C no stack", state: "failed", err: { message: "mC only" } },
                { title: "D long stack truncated", state: "failed", err: { message: "mD", estack: longStack } },
              ],
            },
          ],
        },
      ],
    });

    const result = cypressAdapter.collect({ root: TEST_ROOT, reportsDir });
    const truncatedD = `${longStack.slice(0, 4000)}\n/* ...truncated... */`;

    assert.deepStrictEqual(result, {
      testResults: {
        found: true,
        totals: { tests: 4, passed: 0, failed: 4, pending: 0, duration: 4 },
        specs: [{ specFile: "cypress/e2e/tests/s4_errors.cy.js", tests: 4, passed: 0, failed: 4, pending: 0, duration: 4 }],
      },
      failedTests: [
        { title: "A estack wins", fullTitle: null, suite: "S4 Suite", specFile: "cypress/e2e/tests/s4_errors.cy.js", status: "failed", duration: null, error: { message: "mA", stack: "estackA" }, screenshot: null },
        { title: "B stack fallback", fullTitle: null, suite: "S4 Suite", specFile: "cypress/e2e/tests/s4_errors.cy.js", status: "failed", duration: null, error: { message: "mB", stack: "stackB-only" }, screenshot: null },
        { title: "C no stack", fullTitle: null, suite: "S4 Suite", specFile: "cypress/e2e/tests/s4_errors.cy.js", status: "failed", duration: null, error: { message: "mC only", stack: null }, screenshot: null },
        { title: "D long stack truncated", fullTitle: null, suite: "S4 Suite", specFile: "cypress/e2e/tests/s4_errors.cy.js", status: "failed", duration: null, error: { message: "mD", stack: truncatedD }, screenshot: null },
      ],
      warnings: [],
    });
  } finally {
    fs.rmSync(reportsDir, { recursive: true, force: true });
  }
});

// --- S5: screenshot matrix (captured from oracle commit) --------------
// Protects: missing directory -> null, directory-exists-but-no-match ->
// null, single exact match, highest-numbered retry attempt selected,
// loose-prefix decoys rejected, and special regex characters in the test
// title handled safely (escaped, not interpreted as regex syntax).

test("S5 screenshot matrix: current adapter matches the historical oracle across matching/missing/retry/decoy cases", () => {
  const specFile = "/cypress/e2e/tests/s5_screens.cy.js";
  const suiteTitles = ["S5 Suite"];

  const cases = [
    { label: "no directory", title: "no dir test", screenshots: null, expected: null },
    { label: "no match", title: "no match test", screenshots: { "S5 Suite -- no match test.png": "" }, expected: null },
    {
      label: "single match",
      title: "single test",
      screenshots: { "S5 Suite -- single test (failed).png": "" },
      expected: "cypress/screenshots/s5_screens.cy.js/S5 Suite -- single test (failed).png",
    },
    {
      label: "multiple attempts - highest wins",
      title: "retry test",
      screenshots: { "S5 Suite -- retry test (failed) (1).png": "", "S5 Suite -- retry test (failed) (2).png": "" },
      expected: "cypress/screenshots/s5_screens.cy.js/S5 Suite -- retry test (failed) (2).png",
    },
    {
      label: "loose-prefix decoy rejected",
      title: "prefix test",
      screenshots: { "S5 Suite -- prefix test extra (failed).png": "" },
      expected: null,
    },
    {
      label: "special regex characters in title",
      title: "weird (title) [x]",
      screenshots: { "S5 Suite -- weird (title) [x] (failed).png": "" },
      expected: "cypress/screenshots/s5_screens.cy.js/S5 Suite -- weird (title) [x] (failed).png",
    },
  ];

  // Uses the real cypress/screenshots directory (not an overridden temp
  // dir) for the same ROOT-relative-path reason as S1 above - cleaned up
  // after every case so no residue remains between cases or after the
  // test. Cleanup is scoped to only this test's own "s5_screens.cy.js"
  // subdirectory, never the shared cypress/screenshots root itself - see
  // S1's comment above for why a whole-root deletion here would be
  // unsafe to run concurrently with other test files/cases that share
  // that same root.
  const specDir = path.join(ROOT, "cypress", "screenshots", "s5_screens.cy.js");
  for (const c of cases) {
    try {
      if (c.screenshots) {
        fs.mkdirSync(specDir, { recursive: true });
        for (const [name] of Object.entries(c.screenshots)) fs.writeFileSync(path.join(specDir, name), "");
      }
      const result = cypressAdapter.resolveScreenshotPath(specFile, suiteTitles, c.title, path.join(ROOT, "cypress", "screenshots"), TEST_ROOT);
      assert.equal(result, c.expected, c.label);
    } finally {
      fs.rmSync(specDir, { recursive: true, force: true });
    }
  }
});

// --- S6: missing report directory (captured from oracle commit) -------
// Protects: the exact historical warning text and found:false/[] shape
// when reports/cypress doesn't exist at all.

test("S6 missing report directory: current adapter matches the historical oracle's exact warning and empty result", () => {
  const reportsDir = path.join(tmpReportsDir(), "does-not-exist");
  const result = cypressAdapter.collect({ root: TEST_ROOT, reportsDir });

  assert.deepStrictEqual(result, {
    testResults: { found: false },
    failedTests: [],
    warnings: ["No report directory found at reports/cypress. Run a test script (e.g. npm run chrome) before ai:collect."],
  });
});

// --- S7: empty report directory (captured from oracle commit) ---------
// Protects: a DIFFERENT exact historical warning from S6 when the
// directory exists but contains zero JSON files.

test("S7 empty report directory: current adapter matches the historical oracle's exact (distinct-from-S6) warning", () => {
  const reportsDir = tmpReportsDir();
  try {
    const result = cypressAdapter.collect({ root: TEST_ROOT, reportsDir });

    assert.deepStrictEqual(result, {
      testResults: { found: false },
      failedTests: [],
      warnings: ["reports/cypress exists but contains no JSON report files."],
    });
  } finally {
    fs.rmSync(reportsDir, { recursive: true, force: true });
  }
});

// --- S8: malformed JSON + valid report (captured from oracle commit) --
// Protects: the malformed file is skipped (never thrown), the valid file
// is still processed, and the warning's stable, project-owned portion -
// built via path.join("reports","cypress",filename), so the assertion
// expresses that join call rather than hardcoding an OS-specific
// separator (preserving Windows/Linux equivalence).
//
// RUNTIME_VOLATILE_WARNING_PROJECTION: the tail of this warning
// (`err.message` from JSON.parse's own SyntaxError) is generated by the
// V8 engine, not by this project's code, and its exact English wording
// is not a guaranteed-stable API - it has changed across V8/Node
// versions historically, and this repository's own CI (.github/workflows,
// node-version: 22) already runs a different Node version than the one
// this golden was authored against. Freezing that exact string forever
// would make the #19.7 regression barrier fail on a future Node upgrade
// for a reason that has nothing to do with Cypress-adapter extraction
// correctness - the actual #19.6/#19.7 contract is "the malformed file
// produces a warning naming itself and is skipped", not "V8 phrases JSON
// syntax errors exactly this way". The stable, project-owned prefix
// (built from this project's own literal "reports"/"cypress" path
// segments and filename) IS still frozen exactly; only the engine-
// generated diagnostic tail is excluded from the frozen surface.
function projectMalformedWarningPrefix(warningText, expectedPrefix) {
  return warningText.startsWith(expectedPrefix) && warningText.length > expectedPrefix.length;
}

test("S8 malformed JSON + valid report: current adapter matches the historical oracle - malformed skipped, valid processed, warning ordering preserved", () => {
  const reportsDir = tmpReportsDir();
  try {
    writeReport(reportsDir, "valid.json", {
      stats: { tests: 1, passes: 0, failures: 1, pending: 0, duration: 1 },
      results: [{ file: "/cypress/e2e/tests/s8_valid.cy.js", suites: [{ title: "S8", suites: [], tests: [{ title: "fails", state: "failed", err: { message: "m8" } }] }] }],
    });
    fs.writeFileSync(path.join(reportsDir, "broken.json"), "{ not valid json");

    const result = cypressAdapter.collect({ root: TEST_ROOT, reportsDir });

    assert.deepStrictEqual(
      { testResults: result.testResults, failedTests: result.failedTests },
      {
        testResults: {
          found: true,
          totals: { tests: 1, passed: 0, failed: 1, pending: 0, duration: 1 },
          specs: [{ specFile: "cypress/e2e/tests/s8_valid.cy.js", tests: 1, passed: 0, failed: 1, pending: 0, duration: 1 }],
        },
        failedTests: [
          { title: "fails", fullTitle: null, suite: "S8", specFile: "cypress/e2e/tests/s8_valid.cy.js", status: "failed", duration: null, error: { message: "m8", stack: null }, screenshot: null },
        ],
      }
    );

    // Warnings: stable project-owned prefix frozen exactly; V8's own
    // JSON.parse diagnostic tail deliberately excluded (see
    // RUNTIME_VOLATILE_WARNING_PROJECTION comment above). Still proves
    // exactly one warning, naming exactly the malformed file's relative
    // path, with genuine error detail attached (never an empty tail).
    const expectedPrefix = `Could not parse ${path.join("reports", "cypress", "broken.json")}: `;
    assert.equal(result.warnings.length, 1);
    assert.ok(
      projectMalformedWarningPrefix(result.warnings[0], expectedPrefix),
      `warning should start with "${expectedPrefix}" and include non-empty detail; got: ${result.warnings[0]}`
    );
  } finally {
    fs.rmSync(reportsDir, { recursive: true, force: true });
  }
});

// --- S9: report.json preference (captured from oracle commit) ---------
// Protects: when report.json is present alongside other JSON files, ONLY
// report.json is read - proven via deliberately drastically different
// totals/failures in the ignored file, so accidentally reading it would
// be immediately obvious.

test("S9 report.json preference: current adapter matches the historical oracle - report.json alone is read when present", () => {
  const reportsDir = tmpReportsDir();
  try {
    writeReport(reportsDir, "report.json", {
      stats: { tests: 1, passes: 0, failures: 1, pending: 0, duration: 9 },
      results: [{ file: "/cypress/e2e/tests/s9_preferred.cy.js", suites: [{ title: "S9", suites: [], tests: [{ title: "preferred failure", state: "failed", err: { message: "preferred" } }] }] }],
    });
    writeReport(reportsDir, "other.json", {
      stats: { tests: 99, passes: 99, failures: 99, pending: 99, duration: 9999 },
      results: [{ file: "/cypress/e2e/tests/s9_other.cy.js", suites: [{ title: "S9other", suites: [], tests: [{ title: "should never appear", state: "failed", err: { message: "should not appear" } }] }] }],
    });

    const result = cypressAdapter.collect({ root: TEST_ROOT, reportsDir });

    assert.deepStrictEqual(result, {
      testResults: {
        found: true,
        totals: { tests: 1, passed: 0, failed: 1, pending: 0, duration: 9 },
        specs: [{ specFile: "cypress/e2e/tests/s9_preferred.cy.js", tests: 1, passed: 0, failed: 1, pending: 0, duration: 9 }],
      },
      failedTests: [
        { title: "preferred failure", fullTitle: null, suite: "S9", specFile: "cypress/e2e/tests/s9_preferred.cy.js", status: "failed", duration: null, error: { message: "preferred", stack: null }, screenshot: null },
      ],
      warnings: [],
    });
  } finally {
    fs.rmSync(reportsDir, { recursive: true, force: true });
  }
});

// --- S10: multiple report files, no report.json (captured from oracle) --
// Protects: both files are processed and their totals/failures are
// aggregated correctly. Deliberately does NOT freeze array positional
// order, because that order derives solely from fs.readdirSync()'s
// platform-dependent enumeration, which was never sorted historically
// and #19.6 deliberately preserved unsorted - freezing position here
// would either be flaky across platforms or would hide a real future
// ordering regression behind an artificial sort. See
// MULTI_REPORT_POSITIONAL_ORDER_FROZEN in the #19.7 design.

function projectMultiReportResult(result) {
  return {
    testResults: {
      ...result.testResults,
      specs: [...result.testResults.specs].sort((a, b) => a.specFile.localeCompare(b.specFile)),
    },
    failedTests: [...result.failedTests].sort((a, b) => {
      const ak = `${a.specFile}\0${a.title}`;
      const bk = `${b.specFile}\0${b.title}`;
      return ak.localeCompare(bk);
    }),
    warnings: result.warnings,
  };
}

test("S10 multiple report files: current adapter matches the historical oracle's aggregate totals/membership (order-independent)", () => {
  const reportsDir = tmpReportsDir();
  try {
    writeReport(reportsDir, "a.json", {
      stats: { tests: 1, passes: 0, failures: 1, pending: 0, duration: 10 },
      results: [{ file: "/cypress/e2e/tests/s10_a.cy.js", suites: [{ title: "S10A", suites: [], tests: [{ title: "a fails", state: "failed", err: { message: "mA" } }] }] }],
    });
    writeReport(reportsDir, "b.json", {
      stats: { tests: 1, passes: 0, failures: 1, pending: 0, duration: 20 },
      results: [{ file: "/cypress/e2e/tests/s10_b.cy.js", suites: [{ title: "S10B", suites: [], tests: [{ title: "b fails", state: "failed", err: { message: "mB" } }] }] }],
    });

    const result = cypressAdapter.collect({ root: TEST_ROOT, reportsDir });
    const projected = projectMultiReportResult(result);

    // Golden (order-independent projection - see function comment above).
    assert.deepStrictEqual(projected, {
      testResults: {
        found: true,
        totals: { tests: 2, passed: 0, failed: 2, pending: 0, duration: 30 },
        specs: [
          { specFile: "cypress/e2e/tests/s10_a.cy.js", tests: 1, passed: 0, failed: 1, pending: 0, duration: 10 },
          { specFile: "cypress/e2e/tests/s10_b.cy.js", tests: 1, passed: 0, failed: 1, pending: 0, duration: 20 },
        ],
      },
      failedTests: [
        { title: "a fails", fullTitle: null, suite: "S10A", specFile: "cypress/e2e/tests/s10_a.cy.js", status: "failed", duration: null, error: { message: "mA", stack: null }, screenshot: null },
        { title: "b fails", fullTitle: null, suite: "S10B", specFile: "cypress/e2e/tests/s10_b.cy.js", status: "failed", duration: null, error: { message: "mB", stack: null }, screenshot: null },
      ],
      warnings: [],
    });

    // Both files were genuinely processed (not just one) - proven
    // independently of whatever order readdirSync happened to return.
    assert.equal(result.failedTests.length, 2);
    assert.equal(result.testResults.specs.length, 2);
  } finally {
    fs.rmSync(reportsDir, { recursive: true, force: true });
  }
});
